# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

from os import remove
import scrapy


class LinkenInItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()

class IndeedItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    job_description = scrapy.Field()
    rating_link = scrapy.Field()
    rating_number = scrapy.Field()
    rating_count = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    number_of_applicants = scrapy.Field()
    remote = scrapy.Field()
    job_type = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()


class CvLibraryItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()

class ReedsItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()



class JobTItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()

class GuardianItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()


class WeWorkItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()


class JobsAcItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()

class CharityItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()

class FindAJobItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()

class TesItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    title = scrapy.Field()
    job_search_role = scrapy.Field()
    job_type = scrapy.Field()
    remote = scrapy.Field()
    company_name = scrapy.Field()
    job_link = scrapy.Field()
    company_link = scrapy.Field()
    location = scrapy.Field()
    time_posted = scrapy.Field()
    time_extracted = scrapy.Field()
    number_of_applicants = scrapy.Field()
    job_description = scrapy.Field()
    criteria_headers = scrapy.Field()
    criteria_des = scrapy.Field()
    others = scrapy.Field()
    salary = scrapy.Field()
    medium = scrapy.Field()
    job_type2 = scrapy.Field()
    job_type1 = scrapy.Field()
    date_posted= scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    county= scrapy.Field()
    avg_sal= scrapy.Field()
    sal_freq= scrapy.Field()
    lower_sal= scrapy.Field()
    higher_sal= scrapy.Field()
